name: dartio_workspace
publish_to: none
repository: https://github.com/bitshifthq/dartio

environment:
  sdk: ^3.11.0

workspace:
  - packages/ptyx

hooks:
  user_defines:
    ptyx:
      source: auto
