import 'dart:io';

import 'package:crypto/crypto.dart';

final _artifactName = RegExp(r'^libptyx-[a-zA-Z0-9_.-]+\.(?:dll|dylib|so)$');
final _releaseTag = RegExp(r'^ptyx-v\d+\.\d+\.\d+$');
const _releaseArtifacts = {
  'libptyx-aarch64-linux-gnu.so',
  'libptyx-aarch64-macos.dylib',
  'libptyx-aarch64-windows.dll',
  'libptyx-x86_64-linux-gnu.so',
  'libptyx-x86_64-macos.dylib',
  'libptyx-x86_64-windows.dll',
};

void main(List<String> arguments) {
  if (arguments.length < 2) {
    stderr.writeln(
      'usage: dart run tool/generate_binary_hash.dart '
      '<release-tag> <output-file> [--check] [native-artifact ...]',
    );
    exitCode = 64;
    return;
  }

  final output = File(arguments[1]).absolute;
  final check = arguments.skip(2).contains('--check');
  final artifacts = arguments
      .skip(2)
      .where((argument) => argument != '--check')
      .map((path) => File(path).absolute);
  final source = generateAssetHashesSource(
    releaseTag: arguments.first,
    artifacts: artifacts,
  );
  if (check) {
    if (!assetHashesAreCurrent(output, source)) {
      stderr.writeln(
        '${output.path} is stale. Regenerate it with '
        'tool/generate_binary_hash.dart.',
      );
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(source);
}

/// Whether [output] contains the exact generated [source].
bool assetHashesAreCurrent(File output, String source) =>
    output.existsSync() && output.readAsStringSync() == source;

/// Generates the Dart manifest for an explicit set of release artifacts.
///
/// Requiring explicit files prevents release tooling from signing unrelated
/// files that happen to share an artifact directory.
String generateAssetHashesSource({
  required String releaseTag,
  required Iterable<File> artifacts,
}) {
  if (!_releaseTag.hasMatch(releaseTag)) {
    throw FormatException(
      'Release tag must have the form ptyx-v<major>.<minor>.<patch>.',
      releaseTag,
    );
  }

  final hashes = <String, String>{};
  for (final artifact in artifacts) {
    if (!artifact.existsSync()) {
      throw ArgumentError.value(
        artifact.path,
        'artifacts',
        'Artifact does not exist',
      );
    }
    final filename = artifact.uri.pathSegments.last;
    if (!_artifactName.hasMatch(filename) ||
        !_releaseArtifacts.contains(filename)) {
      throw FormatException('Unsupported ptyx artifact filename.', filename);
    }
    if (hashes.containsKey(filename)) {
      throw ArgumentError.value(
        filename,
        'artifacts',
        'Artifact filenames must be unique',
      );
    }
    hashes[filename] = sha256.convert(artifact.readAsBytesSync()).toString();
  }

  final entries = hashes.entries.toList()
    ..sort((left, right) => left.key.compareTo(right.key));
  final buffer = StringBuffer()
    ..writeln('// --- DO NOT EDIT MANUALLY ---')
    ..writeln(
      '// This file contains hashes of ptyx binaries downloaded by the build '
      'hook.',
    );
  if (entries.isEmpty) {
    buffer
      ..writeln(
        '// For this source-first release, no prebuilt binaries are published.',
      )
      ..writeln('//');
  }
  buffer
    ..writeln('// Generated by tool/generate_binary_hash.dart')
    ..writeln()
    ..writeln('// dart format off')
    ..writeln(
      '// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars',
    )
    ..writeln()
    ..writeln('/// The release tag used for downloading prebuilt binaries.')
    ..writeln("const releaseTag = '$releaseTag';")
    ..writeln()
    ..writeln(
      '/// SHA256 hashes for pre-built native binaries. '
      'Keys are artifact filenames.',
    );
  if (entries.isEmpty) {
    buffer.writeln('const assetHashes = <String, String>{};');
  } else {
    buffer.writeln('const assetHashes = <String, String>{');
    for (final entry in entries) {
      buffer.writeln("  '${entry.key}': '${entry.value}',");
    }
    buffer.writeln('};');
  }
  return buffer.toString();
}
