// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

/// Returns the number of live Dart adapters.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_adapter_count();

/// Returns one while attachment is delayed.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_attach_delay_active();

/// Delays the next runtime attachment in diagnostic builds.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void ptyd_test_delay_next_attach(int milliseconds);

/// Delays the next spawn worker in diagnostic builds.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void ptyd_test_delay_next_spawn(int milliseconds);

/// Injects a typed exit-observation failure.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_fail_exit_observation();

/// Forces the next Dart port post to fail.
@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_post();

/// Forces the next admitted write to fail.
@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_write();

/// Terminates the Unix broker; returns one when a broker was terminated.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_kill_broker();

/// Returns the number of sessions tracked by live Dart adapters.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_session_count();

/// Returns one while the diagnostic spawn delay is active.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_spawn_delay_active();
