// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void ptyd_test_delay_next_spawn(int milliseconds);

@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_post();

@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_write();

@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_kill_broker();

@ffi.Native<ffi.Uint64 Function()>()
external int ptyd_test_outstanding_event_count();

@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_spawn_delay_active();
