// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

/// Returns the number of live Dart adapters in this process.
///
/// @return Live adapter count, or UINT32_MAX when the registry is unavailable.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_adapter_count();

/// Reports whether the diagnostic runtime-attachment delay is active.
///
/// @return One while attachment is delayed; otherwise zero.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_attach_delay_active();

/// Delays the next runtime attachment in diagnostic builds.
///
/// @param[in] milliseconds Delay duration.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void ptyd_test_delay_next_attach(int milliseconds);

/// Delays the next spawn worker in diagnostic builds.
///
/// @param[in] milliseconds Delay duration.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void ptyd_test_delay_next_spawn(int milliseconds);

/// Injects a typed exit-observation failure for the sole diagnostic session.
///
/// @return One when the event was posted; otherwise zero.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_fail_exit_observation();

/// Forces the next Dart port post to fail in diagnostic builds.
@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_post();

/// Forces the next admitted write to fail in diagnostic builds.
@ffi.Native<ffi.Void Function()>()
external void ptyd_test_fail_next_write();

/// Terminates the Unix broker in diagnostic builds.
///
/// @return One when a broker was terminated; otherwise zero.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_kill_broker();

/// Returns the number of sessions tracked by live Dart adapters.
///
/// @return Tracked session count, or UINT32_MAX when native state is
/// unavailable.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_session_count();

/// Reports whether the diagnostic spawn delay is active.
///
/// @return One while a delayed worker is active; otherwise zero.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyd_test_spawn_delay_active();
