// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Uint32 Function()>(symbol: 'ptyi_abi_version')
external int controllerAbiVersion();

/// Publishes a staged session after Dart has installed its routing state.
@ffi.Native<ffi.Bool Function(ffi.Uint64)>(symbol: 'ptyi_activate')
external bool controllerActivate(int handle);

/// Capability bits: signals=1, process groups=2, modes=4, ConPTY=8,
/// terminal name=16.
@ffi.Native<ffi.Uint32 Function()>(symbol: 'ptyi_capabilities')
external int controllerCapabilities();

@ffi.Native<ffi.Bool Function(ffi.Uint64)>(symbol: 'ptyi_close')
external bool controllerClose(int handle);

@ffi.Native<ffi.Bool Function(ffi.Uint64, ffi.Size)>(
  symbol: 'ptyi_credit_async',
)
external bool controllerCredit(int handle, int bytes);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>(symbol: 'ptyi_destroy')
external bool controllerDestroy(int handle);

@ffi.Native<ffi.Bool Function(ffi.Uint64, ffi.Pointer<ffi.Int64>)>(
  symbol: 'ptyi_exit_status',
)
external bool controllerExitStatus(int handle, ffi.Pointer<ffi.Int64> status);

/// NativeFinalizer callback. The token is the generation-tagged handle.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'ptyi_finalize')
external void controllerFinalize(ffi.Pointer<ffi.Void> token);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>(symbol: 'ptyi_init')
external bool controllerInit(ffi.Pointer<ffi.Void> dart_initialize_api_dl_data);

/// Returns the calling thread's last synchronous native error, or zero.
@ffi.Native<ffi.Int32 Function()>(symbol: 'ptyi_last_error_code')
external int controllerLastErrorCode();

/// Returns -1 when unavailable, otherwise canonical/echo/signals bits.
@ffi.Native<ffi.Int32 Function(ffi.Uint64)>(symbol: 'ptyi_mode')
external int controllerMode(int handle);

@ffi.Native<ffi.Bool Function(ffi.Uint64, ffi.Bool)>(symbol: 'ptyi_pause')
external bool controllerPause(int handle, bool paused);

@ffi.Native<ffi.Int64 Function(ffi.Uint64)>(symbol: 'ptyi_pid')
external int controllerPid(int handle);

@ffi.Native<
  ffi.Bool Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Uint32, ffi.Uint32)
>(symbol: 'ptyi_resize')
external bool controllerResize(
  int handle,
  int rows,
  int columns,
  int pixel_width,
  int pixel_height,
);

/// Returns 1 when delivered, 0 after exit, and -1 on native failure.
@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Int32)>(symbol: 'ptyi_signal')
external int controllerSignal(int handle, int signal);

@ffi.Native<ffi.Bool Function(ffi.Uint64, ffi.Pointer<ffi.Uint32>)>(
  symbol: 'ptyi_size',
)
external bool controllerSize(int handle, ffi.Pointer<ffi.Uint32> values);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Size,
    ffi.Size,
    ffi.Int64,
    ffi.Int64,
  )
>(symbol: 'ptyi_spawn')
external int controllerSpawn(
  ffi.Pointer<ffi.Char> executable,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arguments,
  int argument_count,
  ffi.Pointer<ffi.Pointer<ffi.Char>> environment,
  int environment_count,
  bool inherit_environment,
  ffi.Pointer<ffi.Char> cwd,
  int rows,
  int columns,
  int pixel_width,
  int pixel_height,
  int input_capacity,
  int output_capacity,
  int output_port,
  int event_port,
);

/// Returns -1 when unavailable. Otherwise returns the required byte count when
/// target is NULL or too small, or the written byte count on success.
@ffi.Native<ffi.IntPtr Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  symbol: 'ptyi_tty_name',
)
external int controllerTtyName(
  int handle,
  ffi.Pointer<ffi.Uint8> target,
  int capacity,
);

/// Wait registration result: 0 failed, 1 ready, 2 armed.
@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Size, ffi.Uint64)>(
  symbol: 'ptyi_wait_capacity',
)
external int controllerWaitCapacity(int handle, int required, int waiter);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>(
  symbol: 'ptyi_wait_flush',
)
external int controllerWaitFlush(int handle, int sequence, int waiter);

/// Returns a nonzero accepted-input sequence, or zero without accepting.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  symbol: 'ptyi_write',
)
external int controllerWrite(
  int handle,
  ffi.Pointer<ffi.Uint8> bytes,
  int length,
);

const int controllerAbiVersionExpected = 3;
