// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

/// @brief Acknowledges one output event after Dart consumes its copied bytes.
///
/// Acknowledgement releases the C event and returns native output credit. Each
/// nonzero token must be acknowledged exactly once.
///
/// @param[in] adapter Owning adapter.
/// @param[in] token Nonzero output-event token.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyd_adapter_t,
    ptyx_event_token_t,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyd_event_ack(
  int adapter,
  int token,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Initializes Dart API-DL for the current library artifact.
///
/// @param[in] api_data Dart NativeApi.initializeApiDLData.
/// @return PTYX_STATUS_OK or PTYX_STATUS_INVALID_ARGUMENT.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Void>)>()
external int ptyd_initialize(ffi.Pointer<ffi.Void> api_data);

/// @brief Attaches the sole event pump and cleanup owner to a runtime.
///
/// @param[in] runtime Live runtime transferred to the adapter on success.
/// @param[in] port Dart native port receiving event arrays.
/// @param[out] adapter Receives the adapter handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
///
/// Each message is an eleven-element Dart array containing kind, session,
/// token, flags, value, error domain, error kind, error operation, native error
/// code, error flags, and nullable Uint8List data, in that order.
/// Output remains bounded by each session's configured native output capacity.
/// Withholding an acknowledgement applies backpressure only to that session;
/// the shared runtime continues fairly delivering other sessions' events.
///
/// After success, detach or finalization owns runtime shutdown and release.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_runtime_t,
    ffi.Int64,
    ffi.Pointer<ptyd_adapter_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyd_runtime_attach(
  int runtime,
  int port,
  ffi.Pointer<ptyd_adapter_t> adapter,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Stops the pump and releases every resource transferred to it.
///
/// Shutdown wakes the blocked event read. The function joins the pump, releases
/// outstanding events and tracked sessions, shuts down and releases the
/// runtime, and clears adapter. Passing an already-zero handle succeeds.
///
/// @param[in,out] adapter Adapter handle, cleared on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ptyd_adapter_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyd_runtime_detach(
  ffi.Pointer<ptyd_adapter_t> adapter,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Native finalizer for an adapter handle encoded as a pointer address.
///
/// Transfers ownership to a process-wide cleanup worker and returns without
/// waiting. The worker performs the same cleanup as detach and ignores
/// diagnostic output because no Dart owner remains.
///
/// @param[in] token Adapter handle encoded as a pointer-sized integer.
/// @return Nothing.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void ptyd_runtime_finalize(ffi.Pointer<ffi.Void> token);

/// @brief Native finalizer for a session handle encoded as a pointer address.
///
/// Transfers ownership to the process-wide cleanup worker and returns without
/// waiting. Cleanup is idempotent and generation checked, so it is safe when
/// explicit close or adapter teardown races finalization.
///
/// @param[in] token Session handle encoded as a pointer-sized integer.
/// @return Nothing.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void ptyd_session_finalize(ffi.Pointer<ffi.Void> token);

/// @brief Explicitly abandons and releases a tracked session.
///
/// @param[in] adapter Owning adapter.
/// @param[in,out] session Tracked handle, cleared on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyd_adapter_t,
    ffi.Pointer<ptyx_session_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyd_session_release(
  int adapter,
  ffi.Pointer<ptyx_session_t> session,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Atomically admits and transfers a session spawn to the adapter.
///
/// The pump cannot process SPAWN_READY or SPAWN_FAILED before it owns the
/// returned handle. The adapter releases the handle after SPAWN_FAILED or
/// CLOSE_COMPLETE, or during detach.
///
/// @param[in] adapter Owning adapter.
/// @param[in] options Validated, borrowed spawn options.
/// @param[out] session Receives the tracked session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyd_adapter_t,
    ffi.Pointer<ptyx_spawn_options_t>,
    ffi.Pointer<ptyx_session_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyd_session_spawn_start(
  int adapter,
  ffi.Pointer<ptyx_spawn_options_t> options,
  ffi.Pointer<ptyx_session_t> session,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Returns the packed ABI major and minor version.
///
/// @return `(major << 16) | minor`.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyx_abi_version();

/// @brief Formats an error into caller-owned UTF-8 storage.
///
/// @param[in] error Error value to format.
/// @param[out] target Destination bytes, or NULL to query the required size.
/// @param[in] capacity Writable bytes at target.
/// @param[out] required Receives the required byte count excluding a trailing
/// NUL. May be NULL.
/// @return PTYX_STATUS_OK when the complete message was written,
/// PTYX_STATUS_BUFFER_TOO_SMALL when capacity is insufficient, or
/// PTYX_STATUS_INVALID_ARGUMENT for an invalid structure or pointer pair.
///
/// A successful write appends a NUL when capacity is greater than required.
/// No message contains spawn arguments, environment values, or input bytes.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ptyx_error_t>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int ptyx_error_format(
  ffi.Pointer<ptyx_error_t> error,
  ffi.Pointer<ffi.Uint8> target,
  int capacity,
  ffi.Pointer<ffi.Uint64> required,
);

/// @brief Releases one transferred event and its output credit.
///
/// @param[in,out] event Event returned by ptyx_runtime_next_event(). Every field
/// except the caller-provided struct_size is reset to zero on success so the
/// structure can be reused.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_STALE_HANDLE for an invalid owning
/// token, or PTYX_STATUS_INVALID_ARGUMENT. A zero-initialized event succeeds.
///
/// @par Thread safety
/// Safe to call from a different thread than event receipt.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<ptyx_event_t>, ffi.Pointer<ptyx_error_t>)
>()
external int ptyx_event_release(
  ffi.Pointer<ptyx_event_t> event,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Returns capabilities implemented by a runtime.
///
/// @param[in] runtime Live runtime handle.
/// @param[out] capabilities Receives PTYX_CAPABILITY_* bits.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or PTYX_STATUS_STALE_HANDLE.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_runtime_t,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_runtime_capabilities(
  int runtime,
  ffi.Pointer<ffi.Uint32> capabilities,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Creates an isolated PTY runtime.
///
/// @param[in] options Runtime options, or NULL for defaults.
/// @param[out] runtime Receives a nonzero generation handle on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
///
/// The operation is transactional. On failure, runtime receives
/// PTYX_INVALID_RUNTIME and no native worker remains owned by the caller.
///
/// @par Blocking
/// May start native worker threads and a Unix broker.
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ptyx_runtime_options_t>,
    ffi.Pointer<ptyx_runtime_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_runtime_create(
  ffi.Pointer<ptyx_runtime_options_t> options,
  ffi.Pointer<ptyx_runtime_t> runtime,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Waits for and transfers ownership of the next fair runtime event.
///
/// @param[in] runtime Live runtime handle.
/// @param[in,out] event Zero-initialized event with struct_size set.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_END_OF_STREAM after shutdown, or a
/// typed failure status.
///
/// Events are selected round-robin from per-session queues. Exactly one
/// logical consumer may call this function for a runtime. Runtime shutdown
/// wakes a blocked consumer. Passing an event that still owns a token returns
/// PTYX_STATUS_WRONG_STATE without changing the event.
///
/// @par Blocking
/// Blocks until an event or runtime shutdown is available.
/// @par Thread safety
/// Other runtime and session functions may run concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_runtime_t,
    ffi.Pointer<ptyx_event>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_runtime_next_event(
  int runtime,
  ffi.Pointer<ptyx_event> event,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Releases a shut-down runtime handle.
///
/// @param[in,out] runtime Live handle to release. Receives
/// PTYX_INVALID_RUNTIME on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_BUSY when shutdown has not converged,
/// or a typed failure status. Passing an already-zero handle succeeds.
///
/// All sessions and transferred events must be released first.
///
/// @par Thread safety
/// Do not race release with any operation using this runtime.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ptyx_runtime_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_runtime_release(
  ffi.Pointer<ptyx_runtime_t> runtime,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Starts deterministic shutdown and wakes the event consumer.
///
/// @param[in] runtime Live runtime handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK when shutdown converged. Repeated calls succeed.
///
/// @par Blocking
/// May wait for native owners and the Unix broker to terminate.
/// @par Thread safety
/// Do not race this function with another shutdown or release.
@ffi.Native<
  ffi.UnsignedInt Function(ptyx_runtime_t, ffi.Pointer<ptyx_error_t>)
>()
external int ptyx_runtime_shutdown(
  int runtime,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Commits drain-and-discard for buffered and future output.
///
/// @param[in] session Live session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
///
/// This operation does not release output events already transferred to the
/// caller. Repeating a successful cancellation for the same live session
/// succeeds without changing state.
@ffi.Native<
  ffi.UnsignedInt Function(ptyx_session_t, ffi.Pointer<ptyx_error_t>)
>()
external int ptyx_session_cancel_output(
  int session,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Starts or joins session close.
///
/// @param[in] session Live session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK when close was accepted, or a typed failure.
///
/// Exactly one PTYX_EVENT_CLOSE_COMPLETE event reports whether every accepted
/// input byte and native owner reached a known terminal state.
@ffi.Native<
  ffi.UnsignedInt Function(ptyx_session_t, ffi.Pointer<ptyx_error_t>)
>()
external int ptyx_session_close(int session, ffi.Pointer<ptyx_error_t> error);

/// @brief Enables or disables terminal mode-change observation.
///
/// @param[in] session Live session handle.
/// @param[in] enabled One to observe changes or zero to stop observation.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_UNSUPPORTED, or a typed failure.
///
/// Observation is inactive by default. Enabling it produces distinct
/// PTYX_EVENT_MODE_CHANGED events. Disabling it stops native polling and does
/// not remove an event already transferred to the caller.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_session_t,
    ffi.Uint32,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_observe_mode(
  int session,
  int enabled,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Releases or abandons a session handle.
///
/// @param[in,out] session Live handle to release. Receives
/// PTYX_INVALID_SESSION on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure. Passing an already-zero handle
/// succeeds.
///
/// Release is nonblocking. If deterministic close has not converged, native
/// ownership continues cleanup independently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ptyx_session_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_release(
  ffi.Pointer<ptyx_session_t> session,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Resizes a live PTY.
///
/// @param[in] session Live session handle.
/// @param[in] size Non-NULL validated size.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_session_t,
    ffi.Pointer<ptyx_size_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_resize(
  int session,
  ffi.Pointer<ptyx_size_t> size,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Captures process, size, mode, and terminal-name metadata atomically.
///
/// @param[in] session Live session handle.
/// @param[in,out] snapshot Initialized snapshot and optional terminal-name
/// storage. Fixed fields and tty_name_required are populated even when the
/// terminal-name buffer is too small.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_BUFFER_TOO_SMALL, or a typed failure.
///
/// PTYX_SNAPSHOT_HAS_MODE makes PTYX_MODE_* bits valid.
/// PTYX_SNAPSHOT_HAS_TTY_NAME makes the terminal-name fields valid. A second
/// call after a size query is a new atomic snapshot.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_session_t,
    ffi.Pointer<ptyx_session_snapshot_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_snapshot(
  int session,
  ffi.Pointer<ptyx_session_snapshot_t> snapshot,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Starts asynchronous PTY session creation.
///
/// @param[in] runtime Live runtime handle.
/// @param[in] options Complete spawn options.
/// @param[out] session Receives a nonzero generation handle on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK after native ownership of the request is established,
/// or a typed failure status.
///
/// Every caller-owned byte is validated and copied before return. Exactly one
/// PTYX_EVENT_SPAWN_READY or PTYX_EVENT_SPAWN_FAILED event follows successful
/// request admission. Releasing the returned handle before readiness cancels
/// or abandons the transaction without leaking a child.
///
/// @par Blocking
/// Does not wait for process creation, broker I/O, or queue capacity.
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_runtime_t,
    ffi.Pointer<ptyx_spawn_options_t>,
    ffi.Pointer<ptyx_session_t>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_spawn_start(
  int runtime,
  ffi.Pointer<ptyx_spawn_options_t> options,
  ffi.Pointer<ptyx_session_t> session,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Requests termination of the owned terminal job.
///
/// @param[in] session Live session handle.
/// @param[in] signal Unix signal number. Windows ignores this value and
/// terminates the owned Job Object.
/// @param[out] delivered Receives one when termination was accepted and zero
/// when the direct child had already exited.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_UNSUPPORTED, or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_session_t,
    ffi.Int32,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ptyx_error_t>,
  )
>()
external int ptyx_session_terminate(
  int session,
  int signal,
  ffi.Pointer<ffi.Uint32> delivered,
  ffi.Pointer<ptyx_error_t> error,
);

/// @brief Accepts a complete input buffer or none of it.
///
/// @param[in] session Live session handle.
/// @param[in] bytes Input bytes. May be NULL only when length is zero.
/// @param[in] length Number of input bytes.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK after bounded native admission,
/// PTYX_STATUS_BACKPRESSURE when bounded admission is temporarily unavailable
/// because of capacity, entry, channel, or concurrent-admission contention, or
/// a terminal failure status.
///
/// Returning success permits immediate reuse or release of caller storage.
/// Success does not mean the child consumed the bytes.
///
/// @par Thread safety
/// Safe to call concurrently. Accepted writes are FIFO by successful
/// admission linearization order.
@ffi.Native<
  ffi.UnsignedInt Function(
    ptyx_session_t,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<ptyx_error_t>,
  )
>(isLeaf: true)
external int ptyx_session_write(
  int session,
  ffi.Pointer<ffi.Uint8> bytes,
  int length,
  ffi.Pointer<ptyx_error_t> error,
);

const int PTYD_INVALID_ADAPTER = 0;

const int PTYX_ABI_VERSION = 1;

const int PTYX_ABI_VERSION_MAJOR = 0;

const int PTYX_ABI_VERSION_MINOR = 1;

const int PTYX_CAPABILITY_CONPTY = 8;

const int PTYX_CAPABILITY_PROCESS_GROUPS = 2;

const int PTYX_CAPABILITY_SIGNALS = 1;

const int PTYX_CAPABILITY_TERMINAL_MODES = 4;

const int PTYX_CAPABILITY_TERMINAL_NAME = 16;

const int PTYX_EVENT_CLOSE_CLEANUP_FAILED = 4;

const int PTYX_EVENT_CLOSE_INPUT_FAILED = 1;

const int PTYX_EVENT_CLOSE_OUTPUT_FAILED = 2;

const int PTYX_INVALID_EVENT_TOKEN = 0;

const int PTYX_INVALID_RUNTIME = 0;

const int PTYX_INVALID_SESSION = 0;

const int PTYX_MODE_CANONICAL = 1;

const int PTYX_MODE_ECHO = 2;

const int PTYX_MODE_SIGNALS = 4;

const int PTYX_SNAPSHOT_HAS_MODE = 1;

const int PTYX_SNAPSHOT_HAS_TTY_NAME = 2;

const int PTYX_SPAWN_INHERIT_ENVIRONMENT = 1;

/// Generation-checked identity of one Dart event-pump adapter.
typedef ptyd_adapter_t = ffi.Uint64;
typedef Dartptyd_adapter_t = int;

/// @brief Immutable borrowed byte sequence.
final class ptyx_bytes_view extends ffi.Struct {
  /// < Borrowed bytes, or NULL when length is zero.
  external ffi.Pointer<ffi.Uint8> data;

  /// < Number of readable bytes at data.
  @ffi.Uint64()
  external int length;
}

typedef ptyx_bytes_view_t = ptyx_bytes_view;

/// @brief Stable value describing one failure.
///
/// This structure owns no pointers. Unknown trailing fields are reserved for
/// compatible ABI growth. Initialize the complete structure to zero and set
/// struct_size before passing it to ptyx.
final class ptyx_error extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_ERROR_DOMAIN_* value.
  @ffi.UnsignedInt()
  external int domain;

  /// < PTYX_ERROR_* value.
  @ffi.UnsignedInt()
  external int kind;

  /// < PTYX_OPERATION_* value.
  @ffi.UnsignedInt()
  external int operation;

  /// < Optional errno or Win32 status, or zero.
  @ffi.Int32()
  external int native_code;

  /// < Reserved error-detail bits.
  @ffi.Uint32()
  external int flags;

  /// < Bounded non-secret numeric context.
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> context;

  /// < Must be zero.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint64> reserved;
}

/// Stable subsystem that reported an error.
sealed class ptyx_error_domain {
  /// No error domain.
  static const PTYX_ERROR_DOMAIN_NONE = 0;

  /// Caller input validation failure.
  static const PTYX_ERROR_DOMAIN_ARGUMENT = 1;

  /// Lifecycle or handle-state failure.
  static const PTYX_ERROR_DOMAIN_STATE = 2;

  /// Terminal input direction failure.
  static const PTYX_ERROR_DOMAIN_INPUT = 3;

  /// Terminal output direction failure.
  static const PTYX_ERROR_DOMAIN_OUTPUT = 4;

  /// Child process operation failure.
  static const PTYX_ERROR_DOMAIN_PROCESS = 5;

  /// Shared runtime infrastructure failure.
  static const PTYX_ERROR_DOMAIN_RUNTIME = 6;

  /// Operating-system boundary failure.
  static const PTYX_ERROR_DOMAIN_OS = 7;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_ERROR_DOMAIN_ENUM_FORCE_32_BIT = 2147483647;
}

/// Stable category of an error.
sealed class ptyx_error_kind {
  /// No error kind.
  static const PTYX_ERROR_NONE = 0;

  /// Invalid caller value or layout.
  static const PTYX_ERROR_INVALID_ARGUMENT = 1;

  /// Retired or unknown generation-checked identity.
  static const PTYX_ERROR_STALE_HANDLE = 2;

  /// Operation rejected by the current lifecycle state.
  static const PTYX_ERROR_WRONG_STATE = 3;

  /// Bounded queue cannot accept the complete operation.
  static const PTYX_ERROR_QUEUE_FULL = 4;

  /// Capability is unavailable on this backend.
  static const PTYX_ERROR_UNSUPPORTED = 5;

  /// Session or direction is terminal.
  static const PTYX_ERROR_CLOSED = 6;

  /// Native or operating-system operation failed.
  static const PTYX_ERROR_NATIVE_FAILURE = 7;

  /// Runtime ownership or event infrastructure was lost.
  static const PTYX_ERROR_INFRASTRUCTURE_LOST = 8;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_ERROR_KIND_ENUM_FORCE_32_BIT = 2147483647;
}

typedef ptyx_error_t = ptyx_error;

/// @brief One event transferred from a runtime.
///
/// The kind determines which fields carry values:
///
/// - PTYX_EVENT_SPAWN_READY has no additional value.
/// - PTYX_EVENT_SPAWN_FAILED carries error.
/// - PTYX_EVENT_OUTPUT carries immutable data, data_length, and an owning
/// token.
/// - PTYX_EVENT_INPUT_FAILED, PTYX_EVENT_OUTPUT_FAILED, and
/// PTYX_EVENT_INFRASTRUCTURE_FAILED carry error.
/// - PTYX_EVENT_OUTPUT_DONE has no additional value.
/// - PTYX_EVENT_EXIT carries the signed platform exit status in value.
/// - PTYX_EVENT_CLOSE_COMPLETE carries PTYX_EVENT_CLOSE_* bits in flags and
/// the highest-priority retained failure in error.
/// - PTYX_EVENT_MODE_CHANGED carries PTYX_MODE_* bits in value.
///
/// Every event identifies its session. Only PTYX_EVENT_OUTPUT has a nonzero
/// token. Its data remains valid until release.
/// Every successful next_event result must be released exactly once, including
/// events with an invalid token. Copying and releasing an owning event twice is
/// invalid.
final class ptyx_event extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_EVENT_* value.
  @ffi.UnsignedInt()
  external int kind;

  /// < Kind-specific PTYX_EVENT_* bits.
  @ffi.Uint32()
  external int flags;

  /// < Must be zero.
  @ffi.Uint32()
  external int reserved0;

  /// < Originating session or spawn request.
  @ptyx_session_t()
  external int session;

  /// < Owning output token, or zero.
  @ptyx_event_token_t()
  external int token;

  /// < Immutable output bytes until release.
  external ffi.Pointer<ffi.Uint8> data;

  /// < Number of readable bytes at data.
  @ffi.Uint64()
  external int data_length;

  /// < Kind-specific signed value.
  @ffi.Int64()
  external int value;

  /// < Kind-specific value error.
  external ptyx_error_t error;

  /// < Must be zero.
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}

/// Stable kind of an event transferred from a runtime.
sealed class ptyx_event_kind {
  /// Spawn committed and the session is ready for operations.
  static const PTYX_EVENT_SPAWN_READY = 1;

  /// Spawn failed and its attempted ownership was reclaimed.
  static const PTYX_EVENT_SPAWN_FAILED = 2;

  /// Ordered terminal output bytes with an owning event token.
  static const PTYX_EVENT_OUTPUT = 3;

  /// Previously accepted terminal input could not be delivered.
  static const PTYX_EVENT_INPUT_FAILED = 4;

  /// Terminal output ended with a native failure.
  static const PTYX_EVENT_OUTPUT_FAILED = 5;

  /// Runtime or process ownership infrastructure was lost.
  static const PTYX_EVENT_INFRASTRUCTURE_FAILED = 6;

  /// Every safely readable output byte was delivered.
  static const PTYX_EVENT_OUTPUT_DONE = 7;

  /// The direct child exited.
  static const PTYX_EVENT_EXIT = 8;

  /// Explicit close reached its terminal cleanup result.
  static const PTYX_EVENT_CLOSE_COMPLETE = 9;

  /// An observed terminal input mode changed.
  static const PTYX_EVENT_MODE_CHANGED = 10;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_EVENT_KIND_ENUM_FORCE_32_BIT = 2147483647;
}

typedef ptyx_event_t = ptyx_event;

/// Generation-checked owning event identity.
typedef ptyx_event_token_t = ffi.Uint64;
typedef Dartptyx_event_token_t = int;

/// Stable operation associated with an error.
sealed class ptyx_operation {
  /// No associated operation.
  static const PTYX_OPERATION_NONE = 0;

  /// Runtime construction.
  static const PTYX_OPERATION_RUNTIME_CREATE = 1;

  /// Runtime shutdown or release.
  static const PTYX_OPERATION_RUNTIME_SHUTDOWN = 2;

  /// Child and terminal spawn.
  static const PTYX_OPERATION_SPAWN = 3;

  /// Terminal input write.
  static const PTYX_OPERATION_WRITE = 4;

  /// Terminal output delivery or cancellation.
  static const PTYX_OPERATION_OUTPUT = 5;

  /// Terminal resize.
  static const PTYX_OPERATION_RESIZE = 6;

  /// Child termination.
  static const PTYX_OPERATION_TERMINATE = 7;

  /// Atomic session metadata snapshot or observation.
  static const PTYX_OPERATION_METADATA = 8;

  /// Session cleanup.
  static const PTYX_OPERATION_CLOSE = 9;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_OPERATION_ENUM_FORCE_32_BIT = 2147483647;
}

/// @brief Runtime creation options.
///
/// On Unix, an empty broker_path selects the integrity-checked broker bundled
/// with this library artifact. A nonempty path must name an executable broker
/// compatible with the library. Windows ignores broker_path. Set flags and
/// reserved fields to zero.
final class ptyx_runtime_options extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < Must be zero.
  @ffi.Uint32()
  external int flags;

  /// < Optional absolute Unix broker path.
  external ptyx_bytes_view_t broker_path;

  /// < Must be zero.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

typedef ptyx_runtime_options_t = ptyx_runtime_options;

/// While the ABI major is zero, callers must require the exact packed version;
/// development releases may replace layouts without a compatibility shim.
/// Beginning with ABI 1.0, major changes are incompatible and minor releases
/// may add symbols, constants, event kinds, or trailing structure fields.
/// Callers must ignore unknown event kinds after releasing the event and must
/// initialize caller-sized structures to zero so a newer library can inspect
/// struct_size safely.
///
/// ABI 0 requires the complete structure layout for the exact packed version.
/// Prefix-compatible fieldwise access and old-caller/new-library tests are
/// required before declaring ABI 1.0.
/// /
/// /** Generation-checked runtime identity.
typedef ptyx_runtime_t = ffi.Uint64;
typedef Dartptyx_runtime_t = int;

/// @brief Reactor-atomic session metadata and terminal-name storage request.
///
/// Initialize the structure to zero, set struct_size, and optionally set
/// tty_name and tty_name_capacity. On return, flags identifies supported
/// values and tty_name_required reports the terminal-name byte count.
final class ptyx_session_snapshot$1 extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_SNAPSHOT_* result bits.
  @ffi.Uint32()
  external int flags;

  /// < Direct child process ID, or -1.
  @ffi.Int64()
  external int pid;

  /// < Reactor-atomic terminal size.
  external ptyx_size_t size;

  /// < PTYX_MODE_* bits.
  @ffi.Uint32()
  external int modes;

  /// < Must be zero.
  @ffi.Uint32()
  external int reserved0;

  /// < Optional caller-owned terminal-name storage.
  external ffi.Pointer<ffi.Uint8> tty_name;

  /// < Writable bytes at tty_name.
  @ffi.Uint64()
  external int tty_name_capacity;

  /// < Required terminal-name byte count.
  @ffi.Uint64()
  external int tty_name_required;

  /// < Must be zero.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

typedef ptyx_session_snapshot_t = ptyx_session_snapshot$1;

/// Generation-checked session identity.
typedef ptyx_session_t = ffi.Uint64;
typedef Dartptyx_session_t = int;

/// @brief PTY size in cells and optional pixels.
final class ptyx_size extends ffi.Struct {
  /// < Terminal rows in the range 1..=32767.
  @ffi.Uint32()
  external int rows;

  /// < Terminal columns in the range 1..=32767.
  @ffi.Uint32()
  external int columns;

  /// < Optional pixel width in 0..=65535.
  @ffi.Uint32()
  external int pixel_width;

  /// < Optional pixel height in 0..=65535.
  @ffi.Uint32()
  external int pixel_height;
}

typedef ptyx_size_t = ptyx_size;

/// @brief Spawn configuration.
///
/// Arguments and environment entries are byte strings without embedded NUL.
/// Unix preserves their native bytes. Windows requires UTF-8. Environment
/// entries use the platform-neutral `NAME=VALUE` form. Set reserved fields to
/// zero. PTYX_SPAWN_INHERIT_ENVIRONMENT requires environment_count to be zero;
/// without it, environment is the complete child environment.
/// At most 256 arguments and 4096 environment entries are accepted. The
/// complete native-encoded spawn payload must not exceed 64 KiB.
/// graceful_close_timeout_us controls Unix graceful-close escalation and must
/// not exceed 60000000. Windows accepts the value but begins Job Object
/// termination immediately because it has no portable graceful request.
final class ptyx_spawn_options extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_SPAWN_* bits.
  @ffi.Uint32()
  external int flags;

  /// < Executable path or lookup name.
  external ptyx_bytes_view_t executable;

  /// < Borrowed argument array.
  external ffi.Pointer<ptyx_bytes_view_t> arguments;

  /// < Number of argument views.
  @ffi.Uint64()
  external int argument_count;

  /// < Borrowed NAME=VALUE array.
  external ffi.Pointer<ptyx_bytes_view_t> environment;

  /// < Number of environment views.
  @ffi.Uint64()
  external int environment_count;

  /// < Directory, or empty for current.
  external ptyx_bytes_view_t working_directory;

  /// < Initial terminal size.
  external ptyx_size_t size;

  /// < Bounded accepted input bytes.
  @ffi.Uint64()
  external int input_capacity;

  /// < Bounded retained output bytes.
  @ffi.Uint64()
  external int output_capacity;

  /// < Unix TERM-to-force interval.
  @ffi.Uint64()
  external int graceful_close_timeout_us;

  /// < Must be zero.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

typedef ptyx_spawn_options_t = ptyx_spawn_options;

/// Stable result of a ptyx operation.
sealed class ptyx_status {
  /// Operation completed successfully.
  static const PTYX_STATUS_OK = 0;

  /// An argument or caller-sized structure is invalid.
  static const PTYX_STATUS_INVALID_ARGUMENT = 1;

  /// A generation-checked handle or token is stale.
  static const PTYX_STATUS_STALE_HANDLE = 2;

  /// The operation is invalid in the current lifecycle state.
  static const PTYX_STATUS_WRONG_STATE = 3;

  /// Bounded input storage cannot accept the complete write now.
  static const PTYX_STATUS_BACKPRESSURE = 4;

  /// The requested capability is unavailable.
  static const PTYX_STATUS_UNSUPPORTED = 5;

  /// The requested direction or session is closed.
  static const PTYX_STATUS_CLOSED = 6;

  /// The blocking event source reached its terminal state.
  static const PTYX_STATUS_END_OF_STREAM = 7;

  /// Ownership is valid but temporarily prevents the operation.
  static const PTYX_STATUS_BUSY = 8;

  /// An operating-system operation failed.
  static const PTYX_STATUS_OS_ERROR = 9;

  /// Runtime infrastructure or an internal invariant failed.
  static const PTYX_STATUS_INTERNAL = 10;

  /// Caller storage is smaller than the reported required length.
  static const PTYX_STATUS_BUFFER_TOO_SMALL = 11;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_STATUS_ENUM_FORCE_32_BIT = 2147483647;
}
