// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;

/// @brief Acknowledges one output event after Dart consumes its copied bytes.
///
/// Acknowledgement releases the C event and returns native output credit. Each
/// nonzero token must be acknowledged exactly once.
///
/// @param[in] adapter Owning adapter.
/// @param[in] token Nonzero output-event token.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(PtydAdapter, PtyxEventToken, ffi.Pointer<PtyxError>)
>()
external int ptyd_event_ack(
  int adapter,
  int token,
  ffi.Pointer<PtyxError> error,
);

/// @brief Initializes Dart API-DL for the current library artifact.
///
/// @param[in] api_data Dart NativeApi.initializeApiDLData.
/// @return PTYX_STATUS_OK or PTYX_STATUS_INVALID_ARGUMENT.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Void>)>()
external int ptyd_initialize(ffi.Pointer<ffi.Void> api_data);

/// @brief Aborts a Dart adapter after a protocol or infrastructure failure.
///
/// Abort uses the same idempotent ownership path as detach. Outstanding event
/// leases, tracked sessions, and the C runtime remain registered when cleanup
/// reports a busy or internal result. The native cleanup worker retries those
/// resources without requiring a Dart isolate.
///
/// @param[in,out] adapter Adapter handle, cleared only after complete cleanup.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<PtydAdapter>, ffi.Pointer<PtyxError>)
>()
external int ptyd_runtime_abort(
  ffi.Pointer<PtydAdapter> adapter,
  ffi.Pointer<PtyxError> error,
);

/// @brief Attaches the sole event pump and cleanup owner to a runtime.
///
/// @param[in] runtime Live runtime transferred to the adapter on success.
/// @param[in] port Dart native port receiving event arrays.
/// @param[out] adapter Receives the adapter handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
///
/// Each message is a nine-element Dart array containing kind, session, token,
/// flags, value, error domain, error kind, native error code, and nullable
/// Uint8List data, in that order.
/// The adapter owns output-token registration and release. The Dart side keeps
/// only a fixed message-shape guard for ABI safety; unknown or malformed port
/// messages converge through the adapter abort operation.
/// Output remains bounded by each session's configured native output capacity.
/// Withholding an acknowledgement applies backpressure only to that session;
/// the shared runtime continues fairly delivering other sessions' events.
///
/// After success, detach or finalization owns runtime shutdown and release.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxRuntime,
    ffi.Int64,
    ffi.Pointer<PtydAdapter>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyd_runtime_attach(
  int runtime,
  int port,
  ffi.Pointer<PtydAdapter> adapter,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns capabilities for an attached Dart runtime adapter.
///
/// @param[in] adapter Attached runtime adapter.
/// @param[out] capabilities Receives PTYX_CAPABILITY_* bits.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_STALE_HANDLE, or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtydAdapter,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyd_runtime_capabilities(
  int adapter,
  ffi.Pointer<ffi.Uint32> capabilities,
  ffi.Pointer<PtyxError> error,
);

/// @brief Stops the pump and releases every resource transferred to it.
///
/// Shutdown wakes the blocked event read. The function joins the pump, releases
/// outstanding events and tracked sessions, shuts down and releases the
/// runtime, and clears adapter. Passing an already-zero handle succeeds.
///
/// @param[in,out] adapter Adapter handle, cleared on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure. A failure leaves the adapter
/// registered so the caller can retry cleanup.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<PtydAdapter>, ffi.Pointer<PtyxError>)
>()
external int ptyd_runtime_detach(
  ffi.Pointer<PtydAdapter> adapter,
  ffi.Pointer<PtyxError> error,
);

/// @brief Native finalizer for an adapter handle encoded as a pointer address.
///
/// Transfers ownership to a process-wide cleanup worker and returns without
/// waiting. The worker performs the same cleanup as detach and ignores
/// diagnostic output because no Dart owner remains.
///
/// @param[in] token Adapter handle encoded as a pointer-sized integer.
/// @return Nothing.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void ptyd_runtime_finalize(ffi.Pointer<ffi.Void> token);

/// @brief Native finalizer for a session handle encoded as a pointer address.
///
/// Transfers ownership to the process-wide cleanup worker and returns without
/// waiting. Cleanup is idempotent and generation checked, so it is safe when
/// explicit close or adapter teardown races finalization.
///
/// @param[in] token Session handle encoded as a pointer-sized integer.
/// @return Nothing.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void ptyd_session_finalize(ffi.Pointer<ffi.Void> token);

/// @brief Explicitly abandons and releases a tracked session.
///
/// @param[in] adapter Owning adapter.
/// @param[in,out] session Tracked handle, cleared on successful or stale
/// release.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure. A failure leaves the session
/// tracked and its ownership available for a later release attempt.
///
/// A busy or internal result leaves ownership tracked so the native cleanup
/// worker can retry it.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtydAdapter,
    ffi.Pointer<PtyxSession>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyd_session_release(
  int adapter,
  ffi.Pointer<PtyxSession> session,
  ffi.Pointer<PtyxError> error,
);

/// @brief Atomically admits and transfers a session spawn to the adapter.
///
/// The pump cannot process SPAWN_READY or SPAWN_FAILED before it owns the
/// returned handle. The adapter releases the handle after SPAWN_FAILED or
/// CLOSE_COMPLETE, or during detach.
///
/// @param[in] adapter Owning adapter.
/// @param[in] options Validated, borrowed spawn options.
/// @param[out] session Receives the tracked session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtydAdapter,
    ffi.Pointer<PtyxSpawnOptions>,
    ffi.Pointer<PtyxSession>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyd_session_spawn_start(
  int adapter,
  ffi.Pointer<PtyxSpawnOptions> options,
  ffi.Pointer<PtyxSession> session,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns the packed ABI major and minor version.
///
/// @return `(major << 16) | minor`.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<ffi.Uint32 Function()>()
external int ptyx_abi_version();

/// @brief Formats an error into caller-owned UTF-8 storage.
///
/// @param[in] error Error value to format.
/// @param[out] target Destination bytes, or NULL to query the required size.
/// @param[in] capacity Writable bytes at target.
/// @param[out] required Receives the required byte count excluding a trailing
/// NUL. May be NULL.
/// @return PTYX_STATUS_OK when the complete message was written,
/// PTYX_STATUS_BUFFER_TOO_SMALL when capacity is insufficient, or
/// PTYX_STATUS_INVALID_ARGUMENT for an invalid structure or pointer pair.
///
/// A successful write appends a NUL when capacity is greater than required.
/// No message contains spawn arguments, environment values, or input bytes.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<PtyxError>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int ptyx_error_format(
  ffi.Pointer<PtyxError> error,
  ffi.Pointer<ffi.Uint8> target,
  int capacity,
  ffi.Pointer<ffi.Uint64> required,
);

/// @brief Releases one transferred event and its output credit.
///
/// @param[in,out] event Event returned by ptyx_runtime_next_event(). Every field
/// except the caller-provided struct_size is reset to zero on success so the
/// structure can be reused.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_STALE_HANDLE for an invalid owning
/// token, or PTYX_STATUS_INVALID_ARGUMENT. A zero-initialized event succeeds.
///
/// @par Thread safety
/// Safe to call from a different thread than event receipt.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<PtyxEvent>, ffi.Pointer<PtyxError>)
>()
external int ptyx_event_release(
  ffi.Pointer<PtyxEvent> event,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns capabilities implemented by a runtime.
///
/// @param[in] runtime Live runtime handle.
/// @param[out] capabilities Receives PTYX_CAPABILITY_* bits.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or PTYX_STATUS_STALE_HANDLE.
///
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxRuntime,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_runtime_capabilities(
  int runtime,
  ffi.Pointer<ffi.Uint32> capabilities,
  ffi.Pointer<PtyxError> error,
);

/// @brief Creates an isolated PTY runtime.
///
/// @param[in] options Runtime options, or NULL for defaults.
/// @param[out] runtime Receives a nonzero generation handle on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
///
/// The operation is transactional. On failure, runtime receives
/// PTYX_INVALID_RUNTIME and no native worker remains owned by the caller.
///
/// @par Blocking
/// May start native worker threads and a Unix broker.
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<PtyxRuntimeOptions>,
    ffi.Pointer<PtyxRuntime>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_runtime_create(
  ffi.Pointer<PtyxRuntimeOptions> options,
  ffi.Pointer<PtyxRuntime> runtime,
  ffi.Pointer<PtyxError> error,
);

/// @brief Waits for and transfers ownership of the next fair runtime event.
///
/// @param[in] runtime Live runtime handle.
/// @param[in,out] event Zero-initialized event with struct_size set.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_END_OF_STREAM after shutdown, or a
/// typed failure status.
///
/// Events are selected round-robin from per-session queues. Exactly one
/// logical consumer may call this function for a runtime. Runtime shutdown
/// wakes a blocked consumer. Passing an event that still owns a token returns
/// PTYX_STATUS_WRONG_STATE without changing the event.
///
/// @par Blocking
/// Blocks until an event or runtime shutdown is available.
/// @par Thread safety
/// Other runtime and session functions may run concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxRuntime,
    ffi.Pointer<PtyxEvent>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_runtime_next_event(
  int runtime,
  ffi.Pointer<PtyxEvent> event,
  ffi.Pointer<PtyxError> error,
);

/// @brief Releases a shut-down runtime handle.
///
/// @param[in,out] runtime Live handle to release. Receives
/// PTYX_INVALID_RUNTIME on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_BUSY when shutdown has not converged,
/// or a typed failure status. Passing an already-zero handle succeeds.
///
/// All sessions and transferred events must be released first.
///
/// @par Thread safety
/// Do not race release with any operation using this runtime.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<PtyxRuntime>, ffi.Pointer<PtyxError>)
>()
external int ptyx_runtime_release(
  ffi.Pointer<PtyxRuntime> runtime,
  ffi.Pointer<PtyxError> error,
);

/// @brief Starts deterministic shutdown and wakes the event consumer.
///
/// @param[in] runtime Live runtime handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK when shutdown converged. Repeated calls succeed.
///
/// @par Blocking
/// May wait for native owners and the Unix broker to terminate.
/// @par Thread safety
/// Do not race this function with another shutdown or release.
@ffi.Native<ffi.UnsignedInt Function(PtyxRuntime, ffi.Pointer<PtyxError>)>()
external int ptyx_runtime_shutdown(int runtime, ffi.Pointer<PtyxError> error);

/// @brief Commits drain-and-discard for buffered and future output.
///
/// @param[in] session Live session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
///
/// This operation does not release output events already transferred to the
/// caller. Repeating a successful cancellation for the same live session
/// succeeds without changing state.
@ffi.Native<ffi.UnsignedInt Function(PtyxSession, ffi.Pointer<PtyxError>)>()
external int ptyx_session_cancel_output(
  int session,
  ffi.Pointer<PtyxError> error,
);

/// @brief Starts or joins session close.
///
/// @param[in] session Live session handle.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK when close was accepted, or a typed failure.
///
/// Exactly one PTYX_EVENT_CLOSE_COMPLETE event reports whether every accepted
/// input byte and native owner reached a known terminal state.
@ffi.Native<ffi.UnsignedInt Function(PtyxSession, ffi.Pointer<PtyxError>)>()
external int ptyx_session_close(int session, ffi.Pointer<PtyxError> error);

/// @brief Returns the direct-child process identifier.
///
/// @param[in] session Live session handle.
/// @param[out] pid Receives the identifier, or -1 when the backend has no
/// direct-child identifier.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed query failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<ffi.Int64>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_get_child_pid(
  int session,
  ffi.Pointer<ffi.Int64> pid,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns the current terminal dimensions.
///
/// @param[in] session Live session handle.
/// @param[out] size Receives cell and pixel dimensions.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed query failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<PtyxSize>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_get_size(
  int session,
  ffi.Pointer<PtyxSize> size,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns terminal mode bits.
///
/// @param[in] session Live session handle.
/// @param[out] mode Receives PTYX_MODE_* bits.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_UNSUPPORTED when terminal modes are not
/// available, or a typed query failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_get_term_mode(
  int session,
  ffi.Pointer<ffi.Uint32> mode,
  ffi.Pointer<PtyxError> error,
);

/// @brief Returns the controller terminal name in caller-owned storage.
///
/// @param[in] session Live session handle.
/// @param[out] name Destination bytes, or NULL when capacity is zero.
/// @param[in] capacity Writable bytes at name.
/// @param[out] required Receives the byte count excluding a NUL terminator.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_BUFFER_TOO_SMALL after writing required,
/// PTYX_STATUS_UNSUPPORTED when no stable terminal name exists, or a typed
/// query failure.
///
/// Passing a null name with zero capacity performs a size query. The returned
/// bytes are not NUL terminated.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint64>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_get_tty_name(
  int session,
  ffi.Pointer<ffi.Uint8> name,
  int capacity,
  ffi.Pointer<ffi.Uint64> required,
  ffi.Pointer<PtyxError> error,
);

/// @brief Enables or disables terminal mode-change observation.
///
/// @param[in] session Live session handle.
/// @param[in] enabled One to observe changes or zero to stop observation.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_UNSUPPORTED, or a typed failure.
///
/// Observation is inactive by default. Enabling it produces distinct
/// PTYX_EVENT_MODE_CHANGED events. Disabling it stops native polling and does
/// not remove an event already transferred to the caller.
@ffi.Native<
  ffi.UnsignedInt Function(PtyxSession, ffi.Uint32, ffi.Pointer<PtyxError>)
>()
external int ptyx_session_observe_mode(
  int session,
  int enabled,
  ffi.Pointer<PtyxError> error,
);

/// @brief Releases or abandons a session handle.
///
/// @param[in,out] session Live handle to release. Receives
/// PTYX_INVALID_SESSION on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure. Passing an already-zero handle
/// succeeds.
///
/// Release is nonblocking. If deterministic close has not converged, native
/// ownership continues cleanup independently.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<PtyxSession>, ffi.Pointer<PtyxError>)
>()
external int ptyx_session_release(
  ffi.Pointer<PtyxSession> session,
  ffi.Pointer<PtyxError> error,
);

/// @brief Resizes a live PTY.
///
/// @param[in] session Live session handle.
/// @param[in] size Non-NULL validated size.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK or a typed failure status.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<PtyxSize>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_resize(
  int session,
  ffi.Pointer<PtyxSize> size,
  ffi.Pointer<PtyxError> error,
);

/// @brief Starts asynchronous PTY session creation.
///
/// @param[in] runtime Live runtime handle.
/// @param[in] options Complete spawn options.
/// @param[out] session Receives a nonzero generation handle on success.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK after native ownership of the request is established,
/// or a typed failure status.
///
/// Every caller-owned byte is validated and copied before return. Exactly one
/// PTYX_EVENT_SPAWN_READY or PTYX_EVENT_SPAWN_FAILED event follows successful
/// request admission. Releasing the returned handle before readiness cancels
/// or abandons the transaction without leaking a child.
///
/// @par Blocking
/// Does not wait for process creation, broker I/O, or queue capacity.
/// @par Thread safety
/// Safe to call concurrently.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxRuntime,
    ffi.Pointer<PtyxSpawnOptions>,
    ffi.Pointer<PtyxSession>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_spawn_start(
  int runtime,
  ffi.Pointer<PtyxSpawnOptions> options,
  ffi.Pointer<PtyxSession> session,
  ffi.Pointer<PtyxError> error,
);

/// @brief Requests termination of the owned terminal job.
///
/// @param[in] session Live session handle.
/// @param[in] signal Unix signal number. Windows ignores this value and
/// terminates the owned Job Object.
/// @param[out] delivered Receives one when termination was accepted and zero
/// when the direct child had already exited.
/// @param[out] error Optional initialized error destination.
/// @return PTYX_STATUS_OK, PTYX_STATUS_UNSUPPORTED, or a typed failure.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Int32,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<PtyxError>,
  )
>()
external int ptyx_session_terminate(
  int session,
  int signal,
  ffi.Pointer<ffi.Uint32> delivered,
  ffi.Pointer<PtyxError> error,
);

/// @brief Accepts a complete input buffer or none of it.
///
/// @param[in] session Live session handle.
/// @param[in] bytes Input bytes. May be NULL only when length is zero.
/// @param[in] length Number of input bytes.
/// @param[in,out] error Optional initialized error destination. Receives a
/// value on failure and remains unchanged on success so the input hot path
/// performs no error-structure stores.
/// @return PTYX_STATUS_OK after bounded native admission,
/// PTYX_STATUS_BACKPRESSURE when bounded admission is temporarily unavailable
/// because of capacity, entry, channel, or concurrent-admission contention, or
/// a terminal failure status.
///
/// Returning success permits immediate reuse or release of caller storage.
/// Success does not mean the child consumed the bytes.
///
/// @par Thread safety
/// Safe to call concurrently. Accepted writes are FIFO by successful
/// admission linearization order.
@ffi.Native<
  ffi.UnsignedInt Function(
    PtyxSession,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<PtyxError>,
  )
>(isLeaf: true)
external int ptyx_session_write(
  int session,
  ffi.Pointer<ffi.Uint8> bytes,
  int length,
  ffi.Pointer<PtyxError> error,
);

const int PTYD_INVALID_ADAPTER = 0;

const int PTYX_ABI_VERSION = 5;

const int PTYX_ABI_VERSION_MAJOR = 0;

const int PTYX_ABI_VERSION_MINOR = 5;

const int PTYX_CAPABILITY_CONPTY = 8;

const int PTYX_CAPABILITY_PROCESS_GROUPS = 2;

const int PTYX_CAPABILITY_SIGNALS = 1;

const int PTYX_CAPABILITY_TERMINAL_MODES = 4;

const int PTYX_CAPABILITY_TERMINAL_NAME = 16;

const int PTYX_EVENT_CLOSE_CLEANUP_FAILED = 4;

const int PTYX_EVENT_CLOSE_INPUT_FAILED = 1;

const int PTYX_EVENT_CLOSE_OUTPUT_FAILED = 2;

const int PTYX_INVALID_EVENT_TOKEN = 0;

const int PTYX_INVALID_RUNTIME = 0;

const int PTYX_INVALID_SESSION = 0;

const int PTYX_MODE_CANONICAL = 1;

const int PTYX_MODE_ECHO = 2;

const int PTYX_MODE_SIGNALS = 4;

const int PTYX_SPAWN_INHERIT_ENVIRONMENT = 1;

/// Generation-checked identity of one Dart event-pump adapter.
typedef PtydAdapter = ffi.Uint64;
typedef DartPtydAdapter = int;

/// @brief Immutable borrowed byte sequence.
final class PtyxBytesView extends ffi.Struct {
  /// < Borrowed bytes, or NULL when length is zero.
  external ffi.Pointer<ffi.Uint8> data;

  /// < Number of readable bytes at data.
  @ffi.Uint64()
  external int length;

  static ffi.Pointer<PtyxBytesView> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> data,
    required int length,
  }) => $allocator<PtyxBytesView>()
    ..ref.data = data
    ..ref.length = length;
}

/// @brief Stable value describing one failure.
///
/// The operation is identified by the calling function or event kind, so the
/// ABI carries only the domain, category, and optional operating-system code.
/// This structure owns no pointers. Unknown trailing fields are reserved for
/// compatible ABI growth. Initialize the complete structure to zero and set
/// struct_size before passing it to ptyx.
final class PtyxError extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_ERROR_DOMAIN_* value.
  @ffi.UnsignedInt()
  external int domain;

  /// < PTYX_ERROR_* value.
  @ffi.UnsignedInt()
  external int kind;

  /// < Optional errno or Win32 status, or zero.
  @ffi.Int32()
  external int native_code;

  static ffi.Pointer<PtyxError> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int domain,
    required int kind,
    required int native_code,
  }) => $allocator<PtyxError>()
    ..ref.struct_size = struct_size
    ..ref.domain = domain
    ..ref.kind = kind
    ..ref.native_code = native_code;
}

/// Stable subsystem that reported an error.
sealed class PtyxErrorDomain {
  /// No error domain.
  static const PTYX_ERROR_DOMAIN_NONE = 0;

  /// Caller input validation failure.
  static const PTYX_ERROR_DOMAIN_ARGUMENT = 1;

  /// Lifecycle or handle-state failure.
  static const PTYX_ERROR_DOMAIN_STATE = 2;

  /// Terminal input direction failure.
  static const PTYX_ERROR_DOMAIN_INPUT = 3;

  /// Terminal output direction failure.
  static const PTYX_ERROR_DOMAIN_OUTPUT = 4;

  /// Child process operation failure.
  static const PTYX_ERROR_DOMAIN_PROCESS = 5;

  /// Shared runtime infrastructure failure.
  static const PTYX_ERROR_DOMAIN_RUNTIME = 6;

  /// Operating-system boundary failure.
  static const PTYX_ERROR_DOMAIN_OS = 7;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_ERROR_DOMAIN_ENUM_FORCE_32_BIT = 2147483647;
}

/// Stable category of an error.
sealed class PtyxErrorKind {
  /// No error kind.
  static const PTYX_ERROR_NONE = 0;

  /// Invalid caller value or layout.
  static const PTYX_ERROR_INVALID_ARGUMENT = 1;

  /// Retired or unknown generation-checked identity.
  static const PTYX_ERROR_STALE_HANDLE = 2;

  /// Operation rejected by the current lifecycle state.
  static const PTYX_ERROR_WRONG_STATE = 3;

  /// Bounded queue cannot accept the complete operation.
  static const PTYX_ERROR_QUEUE_FULL = 4;

  /// Capability is unavailable on this backend.
  static const PTYX_ERROR_UNSUPPORTED = 5;

  /// Session or direction is terminal.
  static const PTYX_ERROR_CLOSED = 6;

  /// Native or operating-system operation failed.
  static const PTYX_ERROR_NATIVE_FAILURE = 7;

  /// Runtime ownership or event infrastructure was lost.
  static const PTYX_ERROR_INFRASTRUCTURE_LOST = 8;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_ERROR_KIND_ENUM_FORCE_32_BIT = 2147483647;
}

/// @brief One event transferred from a runtime.
///
/// The kind determines which fields carry values:
///
/// - PTYX_EVENT_SPAWN_READY has no additional value.
/// - PTYX_EVENT_SPAWN_FAILED carries error.
/// - PTYX_EVENT_OUTPUT carries immutable data, data_length, and an owning
/// token.
/// - PTYX_EVENT_INPUT_FAILED, PTYX_EVENT_OUTPUT_FAILED,
/// PTYX_EVENT_EXIT_FAILED, and PTYX_EVENT_INFRASTRUCTURE_FAILED carry error.
/// - PTYX_EVENT_OUTPUT_DONE has no additional value.
/// - PTYX_EVENT_EXIT carries the signed platform exit status in value.
/// - PTYX_EVENT_CLOSE_COMPLETE carries PTYX_EVENT_CLOSE_* bits in flags and
/// the highest-priority retained failure in error.
/// - PTYX_EVENT_MODE_CHANGED carries PTYX_MODE_* bits in value.
/// - PTYX_EVENT_MODE_FAILED carries error.
///
/// Every event identifies its session. Only PTYX_EVENT_OUTPUT has a nonzero
/// token. Its data remains valid until release.
/// Every successful next_event result must be released exactly once, including
/// events with an invalid token. Copying and releasing an owning event twice is
/// invalid.
final class PtyxEvent extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_EVENT_* value.
  @ffi.UnsignedInt()
  external int kind;

  /// < Kind-specific PTYX_EVENT_* bits.
  @ffi.Uint32()
  external int flags;

  /// < Must be zero.
  @ffi.Uint32()
  external int reserved0;

  /// < Originating session or spawn request.
  @PtyxSession()
  external int session;

  /// < Owning output token, or zero.
  @PtyxEventToken()
  external int token;

  /// < Immutable output bytes until release.
  external ffi.Pointer<ffi.Uint8> data;

  /// < Number of readable bytes at data.
  @ffi.Uint64()
  external int data_length;

  /// < Kind-specific signed value.
  @ffi.Int64()
  external int value;

  /// < Kind-specific value error.
  external PtyxError error;

  /// < Must be zero.
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}

/// Stable kind of an event transferred from a runtime.
sealed class PtyxEventKind {
  /// Spawn committed and the session is ready for operations.
  static const PTYX_EVENT_SPAWN_READY = 1;

  /// Spawn failed and its attempted ownership was reclaimed.
  static const PTYX_EVENT_SPAWN_FAILED = 2;

  /// Ordered terminal output bytes with an owning event token.
  static const PTYX_EVENT_OUTPUT = 3;

  /// Previously accepted terminal input could not be delivered.
  static const PTYX_EVENT_INPUT_FAILED = 4;

  /// Terminal output ended with a native failure.
  static const PTYX_EVENT_OUTPUT_FAILED = 5;

  /// Runtime or process ownership infrastructure was lost.
  static const PTYX_EVENT_INFRASTRUCTURE_FAILED = 6;

  /// Every safely readable output byte was delivered.
  static const PTYX_EVENT_OUTPUT_DONE = 7;

  /// The direct child exited.
  static const PTYX_EVENT_EXIT = 8;

  /// Explicit close reached its terminal cleanup result.
  static const PTYX_EVENT_CLOSE_COMPLETE = 9;

  /// An observed terminal input mode changed.
  static const PTYX_EVENT_MODE_CHANGED = 10;

  /// Native terminal-mode observation failed and stopped.
  static const PTYX_EVENT_MODE_FAILED = 11;

  /// Direct-child exit-status observation failed.
  static const PTYX_EVENT_EXIT_FAILED = 12;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_EVENT_KIND_ENUM_FORCE_32_BIT = 2147483647;
}

/// Generation-checked owning event identity.
typedef PtyxEventToken = ffi.Uint64;
typedef DartPtyxEventToken = int;

/// While the ABI major is zero, callers must require the exact packed version;
/// development releases may replace layouts without a compatibility shim.
/// Beginning with ABI 1.0, major changes are incompatible and minor releases
/// may add symbols, constants, event kinds, or trailing structure fields.
/// Callers must ignore unknown event kinds after releasing the event and must
/// initialize caller-sized structures to zero so a newer library can inspect
/// struct_size safely.
///
/// ABI 0 requires the complete structure layout for the exact packed version.
/// Prefix-compatible fieldwise access and old-caller/new-library tests are
/// required before declaring ABI 1.0.
/// /
/// /** Generation-checked runtime identity.
typedef PtyxRuntime = ffi.Uint64;
typedef DartPtyxRuntime = int;

/// @brief Runtime creation options.
///
/// On Unix, an empty broker_path selects the integrity-checked broker bundled
/// with this library artifact. A nonempty path must name an executable broker
/// compatible with the library. Windows ignores broker_path. Set flags and
/// reserved fields to zero.
final class PtyxRuntimeOptions extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < Must be zero.
  @ffi.Uint32()
  external int flags;

  /// < Optional absolute Unix broker path.
  external PtyxBytesView broker_path;

  /// < Must be zero.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

/// Generation-checked session identity.
typedef PtyxSession = ffi.Uint64;
typedef DartPtyxSession = int;

/// @brief PTY size in cells and optional pixels.
final class PtyxSize extends ffi.Struct {
  /// < Terminal rows in the range 1..=32767.
  @ffi.Uint32()
  external int rows;

  /// < Terminal columns in the range 1..=32767.
  @ffi.Uint32()
  external int columns;

  /// < Optional pixel width in 0..=65535.
  @ffi.Uint32()
  external int pixel_width;

  /// < Optional pixel height in 0..=65535.
  @ffi.Uint32()
  external int pixel_height;

  static ffi.Pointer<PtyxSize> $allocate(
    ffi.Allocator $allocator, {
    required int rows,
    required int columns,
    required int pixel_width,
    required int pixel_height,
  }) => $allocator<PtyxSize>()
    ..ref.rows = rows
    ..ref.columns = columns
    ..ref.pixel_width = pixel_width
    ..ref.pixel_height = pixel_height;
}

/// @brief Spawn configuration.
///
/// Arguments and environment entries are byte strings without embedded NUL.
/// Unix preserves their native bytes. Windows requires UTF-8. Environment
/// entries use the platform-neutral `NAME=VALUE` form. Set reserved fields to
/// zero. PTYX_SPAWN_INHERIT_ENVIRONMENT requires environment_count to be zero;
/// without it, environment is the complete child environment.
/// At most 256 arguments and 4096 environment entries are accepted. The
/// complete native-encoded spawn payload must not exceed 64 KiB.
/// graceful_close_timeout_us controls Unix graceful-close escalation and must
/// not exceed 60000000. Windows accepts the value but begins Job Object
/// termination immediately because it has no portable graceful request.
final class PtyxSpawnOptions extends ffi.Struct {
  /// < Caller-visible structure size.
  @ffi.Uint32()
  external int struct_size;

  /// < PTYX_SPAWN_* bits.
  @ffi.Uint32()
  external int flags;

  /// < Executable path or lookup name.
  external PtyxBytesView executable;

  /// < Borrowed argument array.
  external ffi.Pointer<PtyxBytesView> arguments;

  /// < Number of argument views.
  @ffi.Uint64()
  external int argument_count;

  /// < Borrowed NAME=VALUE array.
  external ffi.Pointer<PtyxBytesView> environment;

  /// < Number of environment views.
  @ffi.Uint64()
  external int environment_count;

  /// < Directory, or empty for current.
  external PtyxBytesView working_directory;

  /// < Initial terminal size.
  external PtyxSize size;

  /// < Bounded accepted input bytes.
  @ffi.Uint64()
  external int input_capacity;

  /// < Bounded retained output bytes.
  @ffi.Uint64()
  external int output_capacity;

  /// < Unix TERM-to-force interval.
  @ffi.Uint64()
  external int graceful_close_timeout_us;

  /// < Must be zero.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

/// Stable result of a ptyx operation.
sealed class PtyxStatus {
  /// Operation completed successfully.
  static const PTYX_STATUS_OK = 0;

  /// An argument or caller-sized structure is invalid.
  static const PTYX_STATUS_INVALID_ARGUMENT = 1;

  /// A generation-checked handle or token is stale.
  static const PTYX_STATUS_STALE_HANDLE = 2;

  /// The operation is invalid in the current lifecycle state.
  static const PTYX_STATUS_WRONG_STATE = 3;

  /// Bounded input storage cannot accept the complete write now.
  static const PTYX_STATUS_BACKPRESSURE = 4;

  /// The requested capability is unavailable.
  static const PTYX_STATUS_UNSUPPORTED = 5;

  /// The requested direction or session is closed.
  static const PTYX_STATUS_CLOSED = 6;

  /// The blocking event source reached its terminal state.
  static const PTYX_STATUS_END_OF_STREAM = 7;

  /// Ownership is valid but temporarily prevents the operation.
  static const PTYX_STATUS_BUSY = 8;

  /// An operating-system operation failed.
  static const PTYX_STATUS_OS_ERROR = 9;

  /// Runtime infrastructure or an internal invariant failed.
  static const PTYX_STATUS_INTERNAL = 10;

  /// Caller storage is smaller than the reported required length.
  static const PTYX_STATUS_BUFFER_TOO_SMALL = 11;

  /// Reserved value that fixes the public enum representation at 32 bits.
  static const PTYX_STATUS_ENUM_FORCE_32_BIT = 2147483647;
}

/// @deprecated Use PtydAdapter.
typedef ptyd_adapter_t = PtydAdapter;

/// @deprecated Use PtyxBytesView.
typedef ptyx_bytes_view_t = PtyxBytesView;

/// @deprecated Use PtyxError.
typedef ptyx_error_t = PtyxError;

/// @deprecated Use PtyxEvent.
typedef ptyx_event_t = PtyxEvent;

/// @deprecated Use PtyxEventToken.
typedef ptyx_event_token_t = PtyxEventToken;

/// @deprecated Use PtyxRuntimeOptions.
typedef ptyx_runtime_options_t = PtyxRuntimeOptions;

/// @deprecated Use PtyxRuntime.
typedef ptyx_runtime_t = PtyxRuntime;

/// @deprecated Use PtyxSession.
typedef ptyx_session_t = PtyxSession;

/// @deprecated Use PtyxSize.
typedef ptyx_size_t = PtyxSize;

/// @deprecated Use PtyxSpawnOptions.
typedef ptyx_spawn_options_t = PtyxSpawnOptions;
